# @package _group_
_target_: question_classification.models.hier_attn_qc.HierAttnRNN
vocab_size: 100
embedding_dim: 20
low_hidden_size: 40
high_hidden_size: 40
num_classes: 50
max_word_len: 28
max_sentence_len: 37
K: 8
use_highway: True
